### ISSUE TITLE
requireSpacesInAnonymousFunctionExpression: Add exception for shorthand methods

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1513]
See discussion in https://github.com/jscs-dev/node-jscs/issues/1470#issuecomment-118666767

Need to support `allExcept: ['shorthandMethods']`

**Comment by kobezzza** [comment]
+1

Real need 

```js
class Foo {
	constructor(bar) { // Missing space before openning round brace

	}
}
```

**Comment by trikadin** [comment]
+1

**Comment by doombu** [comment]
:+1:

**Comment by markelog** [comment]
Any takers? Should be veeery easy

**Comment by ksheedlo** [comment]
+1

@markelog I'll take it!

**Comment by ksheedlo** [comment]
nevermind, looks like this was fixed in a8296dbfcdf87c7864ade7fe169d19d315552a1e ?

**Comment by ksheedlo** [comment]
This is still broken for me on 2.1.0. Here's my config:

```json
{
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true
  },

  "esnext": true
}
```

My test program:

```js
var o = {
  foo() {
    return 42;
  }
};
```

JSCS output:

```
Missing space before opening round brace at demo.js :
     1 |var o = {
     2 |  foo() {
-------------^
     3 |    return 42;
     4 |  }


1 code style error found.
```

**Comment by markelog** [comment]
> nevermind, looks like this was fixed in a8296db ?

Nope, the opposite :-)

**Comment by aldeed** [comment]
@markelog Given that your last comment acknowledged that https://github.com/jscs-dev/node-jscs/commit/a8296dbfcdf87c7864ade7fe169d19d315552a1e only added tests _proving_ this is still an issue rather than actually fixing this issue, why did you close this issue?

+1 for actually adding an option for this.

**Comment by aldeed** [comment]
Nevermind, I looked at the other commit that actually did fix this, so I see `"allExcept"` now. `"allExcept"` is not in the documentation FYI

**Comment by markelog** [comment]
> "allExcept" is not in the documentation FYI

It is, but there no example for it, if you would like to add, we would accept the pr
