### ISSUE TITLE
does not support async methods

### ISSUE THREAD

**Issue by graingert** [jscs-dev/node-jscs#2270]
Using the airbnb preset with:

```js
import ham from 'ham';

class Foo {
  async blah() {}
}
```

I get:
```
Expected token type "Punctuator" but "Identifier" found at test/webdriver.js :
     1 |import ham from 'ham';
--------^
     2 |
     3 |class Foo {
```

It works fine with:
```js
import ham from 'ham';

async function blah() {};

class Foo {
  blah() { return this::blah(); }
}
```

**Comment by markelog** [comment]
Fixed in cst repo

**Comment by graingert** [comment]
How do I use the cst repo?

**Comment by markelog** [comment]
Wait until cst is updated in jscs, hence this ticket is still open

**Comment by purplecones** [comment]
I still get this issue. See related issue filed with AtomLinter https://github.com/AtomLinter/linter-jscs/issues/282 for more info.

Sample Code:
```javascript
import shortid from 'shortid';

const rootResolvers = () => {
  return {
    Query: {
      async test(root, args, context) {
        return test;
      },
    },
  };
};

export default rootResolvers;
```

JSCS CLI Export:
```
jscs resolvers.js -c airbnb.json
Expected token type "Punctuator" but "Identifier" found at resolvers.js :
     1 |import shortid from 'shortid';
--------^
     2 |
     3 |const rootResolvers = () => {


1 code style error found.
```

```
jscs --version
3.0.7
```

**Comment by markelog** [comment]
Those are different issues - you are talking about object method whereas original issue is about class method, created - https://github.com/cst/cst/issues/133
